AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  go-netlify-functions-sample
  
  Sample SAM Template for go-netlify-functions-sample

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: hello
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
      Environment:
        Variables:
          PARAM1: VALUE
  JsonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: json
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /json
            Method: GET
      Environment:
        Variables:
          PARAM1: VALUE
